name: deploy_staging
concurrency: testnet

on:
  push:
    branches:
      - staging
  pull_request:
    branches:
      - staging
  workflow_dispatch:

jobs:
  deploy-open-offchain:
    name: deployment_staging
    runs-on: ubuntu-20.04
    environment: testnet
    steps:
      - uses: actions/checkout@v2

      - name: AWS SSM Send-Command
        uses: peterkimzz/aws-ssm-send-command@1.0.1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-1
          instance-ids: ${{ secrets.DEPLOY_STAGING_INSTANCE_IDS }}
          working-directory: /home/ubuntu/apps
          command: /bin/sh ./deploy_open.sh > output.log

        # Catch SSM outputs
      - name: Get the outputs
        run: echo "The Command id is ${{ steps.ssm.outputs.command-id }}"
